# Generated by Django 5.1.6 on 2025-03-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('can_view_issues', 'Can view issues'), ('can_resolve_issues', 'Can resolve issues'), ('can_assign_issues', 'Can assign issues')]},
        ),
    ]
