# Generated by Django 5.1.6 on 2025-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(default='products/item.png', upload_to='products/')),
            ],
        ),
    ]
